version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo installing dependencies
      - npm install
  build:
    commands:
      - echo Running tests
      - npm test
      - echo Running building
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
